php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    name: "*.php"
    not-name:
      - "*.blade.php"
      - index.php
      - server.php
  tab-width: 4
  use-tabs: false
js: false
css: false
ts: false
py: false
vue: false
