php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    not-name:
      - index.php
      - server.php
  tab-width: 4
  use-tabs: false
